name: Build Tauri Application

on:
  push:
分支:
      - master  # 或者你想要监控的其他分支

jobs:
  build:
    runs-on: windows-latest  # 你也可以使用 windows-latest 或 macos-latest  

    steps:
      - name: Checkout repository  
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2  
        with:
          node-version: '16'  # 根据你的项目需要的 Node.js 版本进行调整

      - name: Install pnpm
        run: npm install -g pnpm  

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run tauri build

      - name: Get executable file
        run: |
          mkdir -p output
          cp -r src-tauri/target/* output/

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: tauri-executable
          path: output/
