name: Build Tauri App for Windows

on:
  push:
    分支: [ main ]
  pull_request:  
    分支: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2  

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install app dependencies and build web
      run: pnpm install && pnpm build

    - name: Build the app
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: src-tauri/target/release/bundle/msi/  
